services:
  trmnl:
    build:
      context: .
      target: trmnl
    image: trmnl:latest
    restart: unless-stopped
    ports:
      - "8081:8080"
    env_file:
      - .env
    volumes:
      - ./data:/data

  homeassistant:
    build:
      context: .
      target: homeassistant
    image: homeassistant:latest
    restart: unless-stopped
    ports:
      - "8082:8080"
    env_file:
      - .env
